name: Build and Upload Android App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.4
        with:
          java-version: '11'

      - name: Build app
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3.1.2
        with:
          name: apk
          path: app/build/outputs/apk/debug/**.apk

      - name: Upload APK to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1.5.0
        with:
         appId: ${{ secrets.FIREBASE_APP_ID }}
         serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
         file: app/build/outputs/apk/debug/app-debug.apk
