name: Build and Upload Android App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2

      - name: Setup Java JDK
        uses: actions/setup-java@v1.4.4
        with:
          java-version: '11'

      - name: Build app
        run: ./gradlew assembleDebug

      - name: Upload APK
        uses: actions/upload-artifact@v3.1.2
        with:
          name: apk
          path: app/build/outputs/apk/debug/**.apk

      - name: docker-action-send-skype
        # You may pin to the exact commit or the version.
        # uses: Eloco/docker-action-send-skype@6f95f3aba228f3281e3bd6aac48daba3d5598f3d
        uses: Eloco/docker-action-send-skype@v2
        with:
          # the email address which u input to log in
          skype_username: eloco@outlook.com
          # passwd
          skype_password: qwert
          # input both user_id or group_id in skype, also support multiple id which connect by space
          skype_ids: live:.cid.f226e4a7c384157b
          # default is 19:655268b00f704dfc8e71592f93d73bd3@thread.skype 19:06edc5b67f4a48eda7bfdff034918978@thread.skype
          # send all the message in the path [support both folder and file, not support sub-folder]
          send_msg_path: message.txt
          # send all the file in the path [support both folder and file, not support sub-folder]
          send_file_path: app/build/outputs/apk/debug/
          # optional, default is ./downl
